"""Real `node --test` output for `test_quiet_node.py`, and exactly where each line came from.

⭐ **Measured**: `node --test` on Node 24.16.0 (host, NOT a runner image), the practice of
`tests/studyforge/skills/exercises/node_practice.py`, with the `spec` reporter to the console
(the practice's own command). ⛔ **The only edit is the scratch root, made relative as
`LineGate` does.** The runner's exit line is not part of any of them. NODE_FAILURE has two
failing assertions and two passing tests; NODE_ENUM is a solution with an `enum`, which type
stripping refuses.
"""

from __future__ import annotations

NODE_FAILURE = (
    '✔ one space between words (0.58721ms)',
    '✔ blank text is refused (0.294712ms)',
    '✖ inner spaces collapse (0.727202ms)',
    '✖ tabs and newlines count as spaces (0.169257ms)',
    'ℹ tests 4',
    'ℹ suites 0',
    'ℹ pass 2',
    'ℹ fail 2',
    'ℹ cancelled 0',
    'ℹ skipped 0',
    'ℹ todo 0',
    'ℹ duration_ms 64.094252',
    '',
    '✖ failing tests:',
    '',
    'test at practice/normalise.test.ts:13:1',
    '✖ inner spaces collapse (0.727202ms)',
    '  AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:',
    '  ',
    "  'a   b' !== 'a b'",
    '  ',
    '      at TestContext.<anonymous> (file://./practice/normalise.test.ts:14:10)',
    '      at Test.runInAsyncScope (node:async_hooks:227:14)',
    '      at Test.run (node:internal/test_runner/test:1306:25)',
    '      at Test.processPendingSubtests (node:internal/test_runner/test:897:18)',
    '      at Test.postRun (node:internal/test_runner/test:1447:19)',
    '      at Test.run (node:internal/test_runner/test:1372:12)',
    '      at async Test.processPendingSubtests (node:internal/test_runner/test:897:7) {',
    '    generatedMessage: true,',
    "    code: 'ERR_ASSERTION',",
    "    actual: 'a   b',",
    "    expected: 'a b',",
    "    operator: 'strictEqual',",
    "    diff: 'simple'",
    '  }',
    '',
    'test at practice/normalise.test.ts:17:1',
    '✖ tabs and newlines count as spaces (0.169257ms)',
    '  AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:',
    '  ',
    "  'a\\tb\\nc' !== 'a b c'",
    '  ',
    '      at TestContext.<anonymous> (file://./practice/normalise.test.ts:18:10)',
    '      at Test.runInAsyncScope (node:async_hooks:227:14)',
    '      at Test.run (node:internal/test_runner/test:1306:25)',
    '      at Test.processPendingSubtests (node:internal/test_runner/test:897:18)',
    '      at Test.postRun (node:internal/test_runner/test:1447:19)',
    '      at Test.run (node:internal/test_runner/test:1372:12)',
    '      at async Test.processPendingSubtests (node:internal/test_runner/test:897:7) {',
    '    generatedMessage: true,',
    "    code: 'ERR_ASSERTION',",
    "    actual: 'a\\tb\\nc',",
    "    expected: 'a b c',",
    "    operator: 'strictEqual',",
    "    diff: 'simple'",
    '  }',
)

NODE_PASS = (
    '✔ one space between words (0.653934ms)',
    '✔ blank text is refused (0.217838ms)',
    '✔ inner spaces collapse (0.061505ms)',
    '✔ tabs and newlines count as spaces (0.062126ms)',
    'ℹ tests 4',
    'ℹ suites 0',
    'ℹ pass 4',
    'ℹ fail 0',
    'ℹ cancelled 0',
    'ℹ skipped 0',
    'ℹ todo 0',
    'ℹ duration_ms 73.649862',
)

NODE_ENUM = (
    'node:internal/modules/run_main:107',
    '    triggerUncaughtException(',
    '    ^',
    '',
    './practice/normalise.ts:1',
    '  > enum Mode {',
    '      Strict,',
    '  > }',
    '',
    'SyntaxError [ERR_UNSUPPORTED_TYPESCRIPT_SYNTAX]: '
    'TypeScript enum is not supported in strip-only mode',
    '    at parseTypeScript (node:internal/modules/typescript:68:40)',
    '    at processTypeScriptCode (node:internal/modules/typescript:146:42)',
    '    at stripTypeScriptModuleTypes (node:internal/modules/typescript:209:22)',
    '    at Object.getFileProtocolModuleFormat [as file:] '
    '(node:internal/modules/esm/get_format:199:26)',
    '    at defaultGetFormat (node:internal/modules/esm/get_format:262:36)',
    '    at defaultLoadSync (node:internal/modules/esm/load:162:16)',
    '    at #loadAndMaybeBlockOnLoaderThread (node:internal/modules/esm/loader:770:12)',
    '    at #loadSync (node:internal/modules/esm/loader:790:49)',
    '    at ModuleLoader.load (node:internal/modules/esm/loader:756:26)',
    '    at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:488:31) {',
    "  code: 'ERR_UNSUPPORTED_TYPESCRIPT_SYNTAX'",
    '}',
    '',
    'Node.js v24.16.0',
    '✖ practice/normalise.test.ts (46.257998ms)',
    'ℹ tests 1',
    'ℹ suites 0',
    'ℹ pass 0',
    'ℹ fail 1',
    'ℹ cancelled 0',
    'ℹ skipped 0',
    'ℹ todo 0',
    'ℹ duration_ms 54.210717',
    '',
    '✖ failing tests:',
    '',
    'test at practice/normalise.test.ts:1:1',
    '✖ practice/normalise.test.ts (46.257998ms)',
    "  'test failed'",
)
