r"""`container.json` — the deepest container's declaration of what its units are.

**What it does.** Reads one container map: its address, the title of each
level, its single variant, when it was ingested, where in the source it came
from, and the unit list with declared practice counts.

**How you use it.** `parse(text, where, manifest)` and `load(path, manifest)`
return a `Container`; `render(container)` gives back the exact bytes, which is
what makes the round trip a guarantee rather than a hope. ⛔ **The manifest is
required**: a container map is meaningless outside its corpus, because its
address must have the corpus's depth and its variant must be one the corpus
declares.

**Depends on.** `studyforge.address`, `studyforge.corpus.manifest`,
`studyforge.archive.scrub` for R7's gate and `studyforge.version` for R9's.
⛔ **This task builds the reader and the round-trip guarantee. It builds no
writer** — nothing here touches disk except `load`, and nothing writes.

## Who writes this, and what a person may amend

⛔ **Generated by the adapter on ingest** (§6), amended only by the declared
practice counts. The render pipeline never writes it, and nobody writes one
from nothing.

⭐ **"Hand-authorable" is about two fields, not about the document.** What a
person may amend are the **editorial** fields — a corrected `title`, an
explanatory `note` — and a generator that would discard one **stops** (R6).
That is not a hole in a skill: R19 forbids a second source having to *retype*
what a skill could have produced, and a judgement about one's own material is
the one thing no skill can produce. ⛔ Everything derivable — the address, the
titles, the variant, the unit list — is generated, and hand-writing it is a
finding against the adapter-authoring skill.

`render` exists for exactly that round trip: read, amend, write back, and the
bytes of everything untouched are the bytes that were there.

## One variant per container

⚠️ This preserves the invariant that removed a whole failure class: a map
promising a variant the archive does not hold used to be an ambiguous
half-state, and a single-variant container cannot express it.

## `origin` is provenance, and it lives **here** and not in the archive

⭐ **Ruled, closing FND-04's open condition.** `origin` says where in the
source a container and each of its units came from. It is in the container map
and ⛔ **not** in the archive document, because two places to look for one fact
is the defect this project keeps diagnosing — and the archive document already
carries what it needs to stand alone, which is its *identity* (R4), not its
provenance.

⚠️ **It is optional, and that is measured rather than generous.** The
extraction source's equivalent field — `folder` — is present in **116 of 285**
maps. A required `origin` would refuse the other 169 and take V2-03's
migration harness with them.

⛔ **`folder` is `origin`, and it is not `address`.** FND-04 recorded that
`folder` "is exactly what `address` already is, so it is subsumed"; measured
against all 116, **0 are derivable from the titles**. They are truncated and
carry disambiguating suffixes — `…-and-beyond-in-kotlin` where slugifying the
title gives `…-and-beyond`, and `…-usage-1` where it gives `…-usage`. A site's
own URL scheme is not a function of its titles, which is the same reason a
page's name may not be taken from a source filename. So `folder` has a home
here, and the field it needed already existed.

⛔ **A placement profile that needs it must say so and fail loudly when it is
absent** (SF-03). `sibling` does: the Java corpus's directories are flat while
its address is two levels, so the directory comes from `origin` and the
address is *only* identity — a profile using the address for both would create
new directories beside the material, which is what R3 forbids.

## `label` is presentation carried as data

⚠️ **Optional, per unit, and never identity.** Real material carries its own
display numbering — `4.4.1` — while a page's *name* must come from identity,
because two of the four designed source shapes differ only in zero-padding
(`src/1.md` against `src/04.md`) and a reader that took the number from the
filename would have to know which corpus it was reading (R1).

⛔ The address is still the address and the ordinals are still contiguous;
`label` changes only what a unit is **called**. Nothing may parse one back
into an ordinal — R4's argument about paths, applied to numbering.

⭐ **Taken now rather than at M6**, deliberately. §4's YAGNI refuses
flexibility *nobody has asked for*; SF-03 measured a corpus that needs this,
built the consumer, and pinned it against §5's worked example. And R9 makes
the alternative expensive in a way that is not symmetric: adding a field later
is a `container_api` bump, and every map written under the old version is
**refused, never migrated** (R9) until its adapter is re-run.
"""

from __future__ import annotations

from studyforge.corpus.container.document import (
    CONTAINER_API,
    CONTAINER_FILENAME,
    CONTAINER_KEYS,
    EDITORIAL_KEYS,
    KNOWN_CONTAINER_API,
    UNIT_KEYS,
    Container,
    Unit,
    from_document,
    load,
    parse,
    render,
    to_document,
)
from studyforge.corpus.container.errors import ContainerError

__all__ = [
    "CONTAINER_API",
    "CONTAINER_FILENAME",
    "CONTAINER_KEYS",
    "EDITORIAL_KEYS",
    "KNOWN_CONTAINER_API",
    "UNIT_KEYS",
    "Container",
    "ContainerError",
    "Unit",
    "from_document",
    "load",
    "parse",
    "render",
    "to_document",
]
