"""No generated byte stream carries a control character but tab, newline or return.

⛔ **SF-26's third acceptance clause**, and the cheap check that would have caught
the inherited failure outright: a CSS escape in a non-raw Python string, read as an
octal escape, put a control byte into a generated stylesheet; the bytes reproduced
perfectly, the suite stayed green, and every disclosure widget drew a tofu box
until a reader noticed.
"""

from __future__ import annotations

import pytest

from tests.harness import streams

#: Floors on coverage, not counts. ⚠️ Measured 2026-09-10 at `5e608bfc`: **12**
#: emitted streams — the 10 goldens plus the two composed assets — and **28**
#: authorable sources: 15 templates and 13 asset parts. ⚠️ Thirteen of fifteen
#: files in `render/assets/`: the two licences are not parts, because nothing
#: composes them into a page. ⛔ Lower bounds, so adding a template is not a
#: failing test; losing one is.
LEAST_EMITTED = 12
LEAST_AUTHORABLE = 28


@pytest.fixture(scope="module")
def emitted():
    return streams.emitted()


@pytest.fixture(scope="module")
def authorable():
    return streams.authorable()


def test_the_two_populations_are_inhabited_and_say_what_they_reached(emitted, authorable):
    # ⛔ Ruling 191. An empty population reports no offenders, and no offenders is
    # the pass reading — so the sizes come before the verdict, every time.
    for name, data in emitted.items():
        print(f"emitted     {name}  {len(data)} bytes")
    for name, data in authorable.items():
        print(f"authorable  {name}  {len(data)} bytes")
    print(f"emitted {len(emitted)}, authorable {len(authorable)}, scanned {len(streams.scanned())}")
    assert len(emitted) >= LEAST_EMITTED
    assert len(authorable) >= LEAST_AUTHORABLE


def test_nothing_the_tree_emits_carries_a_control_character(emitted):
    # ⛔ The clause itself, over everything a build writes today.
    assert streams.offenders(emitted) == []


def test_nothing_that_can_be_authored_into_a_stream_carries_one_either(authorable):
    # ⚠️ The second population (Ruling 192): a control byte in a template no
    # renderer fills yet, or an asset part no bundle includes yet, is invisible to
    # the emitted census until the day something starts emitting it.
    assert streams.offenders(authorable) == []


def test_every_authorable_source_is_inside_what_is_scanned(emitted, authorable):
    # ⛔ Ruling 192's direction: the SUBSET, never the equality. An emitted stream
    # has no single authorable source — a bundle is several parts, a page is a
    # template plus a document — so equality would fail for a reason that is not a
    # defect. `authorable ⊄ scanned` is the only direction that can hide a file.
    scanned = set(streams.scanned())
    missing = sorted(set(authorable) - scanned)
    print(f"authorable {len(authorable)} ⊆ scanned {len(scanned)}; outside: {missing}")
    assert missing == []
    assert set(emitted) <= scanned


# --------------------------------------------------------------------------
# ⛔ the instrument's own three readings
# --------------------------------------------------------------------------

#: The three shapes of the defect this check exists for. ⛔ The first is the
#: inherited one: a CSS escape written in a NON-RAW Python string — the glyph
#: `\2715` becomes the two characters `chr(0o27)` and `15`, so a stylesheet ships
#: an ETB where a `×` was meant, and the page reproduces it faithfully forever.
#: ⚠️ Spelled here as `chr(...)` and `bytes(...)` rather than as an escape in a
#: literal, so that this file cannot itself be the thing it is looking for.
PLANTS = (
    ("bel", "the inherited octal escape, read as a control byte", bytes([0x07])),
    ("nul", "a NUL in the middle of a page", bytes([0x00])),
    ("nel", "a C1 control: two bytes in utf-8, invisible to a byte scan", chr(0x85)),
)

_IDS = [row[0] for row in PLANTS]


@pytest.mark.parametrize(("why", "plant"), [row[1:] for row in PLANTS], ids=_IDS)
def test_the_scan_catches_a_control_character_planted_in_a_real_stream(emitted, why, plant):
    # ⛔ The planted reading, adversarial to the SEARCH TERM: a real emitted
    # stream, unchanged apart from one character in the middle of it.
    name, clean = next(iter(emitted.items()))
    payload = plant if isinstance(plant, bytes) else plant.encode(streams.ENCODING)
    spoiled = _injected(clean, payload)
    reported = streams.offenders({name: spoiled})
    print(f"{why}: {reported}")
    assert len(reported) == 1
    assert name in reported[0], "a failure must name the stream it was found in"


def test_the_scan_is_silent_on_the_three_characters_that_are_allowed(emitted):
    # ⛔ The impossible reading: a subject that cannot match, and its reading must
    # DIFFER from the pass. ⚠️ It differs the only way a negative check's can —
    # the same three characters are injected in the same place, in the same
    # quantity, and nothing is reported, so the readings above are attributable to
    # WHICH character was planted and not to the planting.
    name, clean = next(iter(emitted.items()))
    allowed = "".join(streams.ALLOWED).encode(streams.ENCODING)
    print(f"injected {len(allowed)} allowed control characters into {name}")
    assert streams.offenders({name: _injected(clean, allowed)}) == []


def _injected(clean: bytes, payload: bytes) -> bytes:
    """`clean` with `payload` inserted after its first line.

    ⛔ At a line boundary rather than at the midpoint: splitting a stream in the
    middle of a multi-byte character would make it undecodable, and the scan would
    then report it for THAT instead — a planted reading that agrees with the
    instrument for the wrong reason is the one species of plant worth nothing.
    """
    cut = clean.index(b"\n") + 1
    return clean[:cut] + payload + clean[cut:]


def test_a_stream_that_is_not_utf_8_is_reported_rather_than_raised():
    # ⚠️ "it has a control character" and "it is not text at all" want the same
    # loud answer, and a scan that raised on the second would take the suite down
    # with a traceback instead of a finding that names the stream.
    reported = streams.offenders({"planted:not-text": bytes([0xFF, 0xFE, 0x41])})
    print(reported)
    assert len(reported) == 1
    assert "not utf-8" in reported[0]
