r"""The consumer-facing capability index — when does capability X become available.

**What it does.** Holds the one map a planner needs about the framework —
every capability, the milestone that delivers it, and what it waits on — and
renders that map as a document. The document is **generated**: a reviewer
regenerates it and gets identical bytes. ⭐ The markdown is read next door, in
`epics`; this module is the index over what that reading produced.

**How you use it.**

    from studyforge.skills.delivery import Index, read_epics, read_sequence

    sequence = read_sequence("README.md", task_index_text)
    index = Index.of(read_epics(documents), sequence)
    index.milestone_of("SK-07")     # when a capability lands
    index.after("M4")               # everything a corpus finishing at M4 forgoes
    index.later("M5", than="M8")    # ⛔ in the declared order, never by id
    index.render()                  # the document

**Depends on.** `dataclasses` and this package's `refusal`. ⛔ Nothing else,
ever — and in particular **not the filesystem**: this module is handed data
and gives back text, so the caller names the documents. A module that went
looking for `docs/tasks/` would be a framework module that knows where a plan
lives, and the next repository's plan does not live there.

## ⛔ Why this exists at all, measured on the filing side

⚠️ **An integration wrote a delivery plan by hand and derived the
capability→milestone map by reading thirteen epic documents** — which is
exactly the cost R14's context budgets exist to prevent, paid again by every
integration, and stale the moment an epic moves. ⭐ **Cost measured where it
was paid: 18 rows of a hand-written plan.**

⛔ **A hand-written index would be that same defect one layer up** (R19: the
consuming half is generated, never hand-authored), which is why this module is
a generator and not a table.

## ⛔ Milestones run in a DECLARED order, which is not the order ids sort to

⚠️ **An id names a gate; it does not say when the gate comes**, and a plan can
be reordered without renaming one. Sorting ids answers *when does X land?* in
an order nobody decided, and drops a milestone no epic delivers anything at.
⭐ **So the order is READ from the document that already declares it** — by
`epics.read_sequence`, named by the caller exactly as the epics are. ⛔ Never
typed a second time here, and never retyped by the next repository (R19).
⭐ **A declared milestone with no capability is printed, and says so.**

## ⛔ `of` names every capability it cannot place, never the first one

⚠️ **Ruling 188** (`W94`). A build over thirteen epic documents that refused
the first id it could not place made the number of rounds it takes to fix the
epics unknowable, and each round is the whole generation. ⭐ **So the nested
walk gathers and the refusal is raised once, after it** — and a single
violation reads exactly as it read before, so nothing that was already right
moved.

## ⚠️ This module names no source and reads no source

⛔ R1: it indexes whatever documents it is given. R20: it never sends a reader
to a path inside the extraction source, and the document it renders carries no
such path — because the whole point of the index is that a consumer stops
having to go and look.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass

from studyforge.skills.delivery.refusal import one_or_all

#: The banner the rendered document opens with. ⛔ A generated document that
#: does not say so is a document somebody edits.
BANNER = "GENERATED by the delivery skill. Do not edit — regenerate."

#: What a declared milestone with no capability says, instead of vanishing.
EMPTY = (
    "⭐ **No epic document declares a capability at this milestone.** It is a gate "
    "in the declared order all the same, and a plan that waits on it waits here."
)


class IndexRefused(Exception):
    """Raised when a document cannot be read as an epic, with the reason."""


@dataclass(frozen=True, slots=True)
class Capability:
    """One thing the framework will be able to do, and when."""

    id: str
    what: str
    milestone: str
    area: str
    epic: str
    depends_on: tuple[str, ...]

    def row(self) -> str:
        """Render as one row of the index's table."""
        waits = ", ".join(f"`{name}`" for name in self.depends_on) or "—"
        return f"| `{self.id}` | {self.what} | {self.area} | {waits} |"


@dataclass(frozen=True, slots=True)
class Epic:
    """One epic document, read as capabilities plus whatever was cancelled."""

    epic: str
    area: str
    capabilities: tuple[Capability, ...]
    cancelled: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class Sequence:
    """The order milestones run in, and the bare name of the document declaring it."""

    name: str
    milestones: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class Index:
    """Every capability the framework will have, ordered by when it lands."""

    epics: tuple[Epic, ...]
    sequence: Sequence

    @classmethod
    def of(cls, epics: Iterable[Epic], sequence: Sequence) -> Index:
        """Build an index, ⛔ naming EVERY duplicate id and EVERY unplaceable one.

        ⛔ `sequence` is required: an index with no declared order would fall
        back to id order without saying so, which is the defect it removes.

        ⛔ **Ruling 188:** the walk gathers and refuses once. Epics carrying
        four misplaced capabilities are refused with four reasons, because
        otherwise the reader learns there were four by running it four times.
        """
        gathered = tuple(epics)
        if not gathered:
            raise IndexRefused("an index of no epics answers every question with silence")
        seen: dict[str, str] = {}
        refusals: list[str] = []
        for epic in gathered:
            for capability in epic.capabilities:
                if capability.id in seen:
                    refusals.append(
                        f"{capability.id} is declared twice — in {seen[capability.id]} "
                        f"and in {epic.epic}"
                    )
                if capability.milestone not in sequence.milestones:
                    refusals.append(
                        f"{capability.id} lands at {capability.milestone}, which "
                        f"{sequence.name} does not declare, so it has no place in the order"
                    )
                seen.setdefault(capability.id, epic.epic)
        if refusals:
            raise IndexRefused(one_or_all(refusals))
        return cls(gathered, sequence)

    @property
    def capabilities(self) -> tuple[Capability, ...]:
        """Every capability, in the order the documents declared them."""
        return tuple(c for epic in self.epics for c in epic.capabilities)

    @property
    def cancelled(self) -> tuple[str, ...]:
        """Every row that declares no milestone, counted rather than dropped."""
        return tuple(name for epic in self.epics for name in epic.cancelled)

    @property
    def milestones(self) -> tuple[str, ...]:
        """Every declared milestone, in the declared order — ⛔ empty ones included."""
        return self.sequence.milestones

    def milestone_of(self, task: str) -> str:
        """When `task` lands. ⛔ Refuses an id the index does not carry."""
        for capability in self.capabilities:
            if capability.id == task:
                return capability.milestone
        raise IndexRefused(f"no such capability — the index carries {len(self.capabilities)}")

    def _position(self, milestone: str) -> int:
        """Say where `milestone` falls in the declared order, refusing one it omits."""
        if milestone not in self.milestones:
            raise IndexRefused(f"no such milestone — the index knows {self.milestones}")
        return self.milestones.index(milestone)

    def later(self, milestone: str, *, than: str) -> bool:
        """Say whether `milestone` comes strictly after `than` in the declared order.

        ⛔ **The one comparison of milestones in this package.** Anything that
        asks *is this later?* asks here, so no caller can compare ids instead.
        """
        return self._position(milestone) > self._position(than)

    def at(self, milestone: str) -> tuple[Capability, ...]:
        """Every capability delivered at `milestone`, in document order."""
        return tuple(c for c in self.capabilities if c.milestone == milestone)

    def after(self, milestone: str) -> tuple[Capability, ...]:
        """Every capability delivered strictly later than `milestone`.

        ⭐ This is what a corpus that finishes at `milestone` will never use,
        and it is the population a terminal statement has to account for.
        """
        self._position(milestone)
        return tuple(c for c in self.capabilities if self.later(c.milestone, than=milestone))

    def render(self) -> str:
        """Render the index as a document, byte-identical on every regeneration."""
        out = [
            "# The capability index",
            "",
            f"**{BANNER}**",
            "",
            "⭐ **What a planner asks the framework, and the only thing it has to "
            "read to find out: *when does capability X become available?***",
            "",
            "⛔ **Derived from the epic documents, never transcribed from them.** "
            "A hand-edit here is a finding against the delivery skill (R19), not "
            "a fix — it is reverted by the next regeneration.",
            "",
            self._derivation(),
            "",
            f"⛔ **Milestones run in the order `{self.sequence.name}` declares, not the "
            f"order their ids sort to:** {' → '.join(f'`{m}`' for m in self.milestones)}.",
            "",
        ]
        for milestone in self.milestones:
            delivered = self.at(milestone)
            counted = "capability" if len(delivered) == 1 else "capabilities"
            out += [f"## {milestone} — {len(delivered)} {counted}", ""]
            if not delivered:
                out += [EMPTY, ""]
                continue
            out += [
                "| capability | what it is | area | waits on |",
                "|---|---|---|---|",
                *(c.row() for c in delivered),
                "",
            ]
        return "\n".join(out)

    def _derivation(self) -> str:
        """Derive the coverage line — ⛔ never a literal somebody typed."""
        dropped = len(self.cancelled)
        empty = sum(1 for milestone in self.milestones if not self.at(milestone))
        return (
            f"**{len(self.capabilities)} capabilities · {len(self.epics)} epic documents · "
            f"{len(self.milestones)} milestones, {empty} with no capability · {dropped} "
            f"cancelled {'row' if dropped == 1 else 'rows'} carried and not counted.**"
        )
