r"""The consumer-facing capability index — when does capability X become available.

**What it does.** Holds the one map a planner needs about the framework —
every capability, the milestone that delivers it, what it waits on, and
⭐ **which side delivers it at all** — and renders that map as a document. The
document is **generated**: a reviewer regenerates it and gets identical bytes.
⭐ Both readings happen next door: the markdown in `epics`, the pin document
in `components`. This module is the index over what they produced.

**How you use it.**

    from studyforge.skills.delivery import Components, Index, read_epics, read_sequence

    sequence = read_sequence("README.md", task_index_text)
    components = Components.read(pins, task_index_text)  # both are TEXT
    index = Index.of(read_epics(documents), sequence, components)
    index.milestone_of("AB-07")     # when a capability lands
    index.after("M4")               # everything a corpus finishing at M4 forgoes
    index.later("M5", than="M8")    # ⛔ in the declared order, never by id
    index.sides["CD-01"]            # ⭐ which side delivers it
    index.render()                  # the document

**Depends on.** `dataclasses` and this package's `components` and `refusal`.
⛔ Nothing else, ever — and in particular **not the filesystem**: this module
is handed data and gives back text, so the caller names the documents. A
module that went looking for `docs/tasks/` would be a framework module that
knows where a plan lives, and the next repository's plan does not live there.

## ⛔ Why this exists at all

⚠️ **A plan written by hand derives the capability→milestone map by reading
every epic document** — a cost paid again by every integration, and stale the
moment an epic moves.

⛔ **A hand-written index would be that same defect one layer up** (R19: the
consuming half is generated, never hand-authored), which is why this module is
a generator and not a table.

## ⛔ Milestones run in a DECLARED order, which is not the order ids sort to

⚠️ **An id names a gate; it does not say when the gate comes**, and a plan can
be reordered without renaming one. Sorting ids answers *when does X land?* in
an order nobody decided, and drops a milestone no epic delivers anything at.
⭐ **So the order is READ from the document that already declares it** — by
`epics.read_sequence`, named by the caller exactly as the epics are. ⛔ Never
typed a second time here, and never retyped by the next repository (R19).
⭐ **A declared milestone with no capability is printed, and says so.**

## ⛔ `of` names every capability it cannot place, never the first one

⚠️ **A refusal names its whole population** (R6). A build that refused the
first id it could not place would make the number of runs it takes to fix the
epics unknowable, and each run is the whole generation. ⭐ **So the nested
walk gathers and the refusal is raised once, after it**, and a single
violation reads as a one-item refusal.

## ⭐ A column that would say the same thing in every row says nothing

⛔ So the side column is rendered only when at least one row is not `HERE`. A
plan whose pin document declares nothing beyond itself renders four
columns — the distinction does not apply there, and a
fifth column of one repeated value is a column nobody reads. ⚠️ What the three
values MEAN, and why the column exists at all, is `components`'.

## ⚠️ This module names no source and reads no source

⛔ R1: it indexes whatever documents it is given. R20: it never sends a reader
to a path inside the extraction source, and the document it renders carries no
such path — because the whole point of the index is that a consumer stops
having to go and look. ⛔ **And no component is ever NAMED in what it
renders**, which is the same rule one layer on: the pin document's names are
read by `components` and never printed here.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass

from studyforge.skills.delivery.components import (
    ELSEWHERE,
    HERE,
    SIDE_COLUMN,
    SIDES,
    UNDECLARED,
    Components,
)
from studyforge.skills.delivery.refusal import one_or_all

#: The banner the rendered document opens with. ⛔ A generated document that
#: does not say so is a document somebody edits.
BANNER = "GENERATED by the delivery skill. Do not edit — regenerate."

#: What a declared milestone with no capability says, instead of vanishing.
EMPTY = (
    "⭐ **No epic document declares a capability at this milestone.** It is a gate "
    "in the declared order all the same, and a plan that waits on it waits here."
)


class IndexRefused(Exception):
    """Raised when a document cannot be read as an epic, with the reason."""


@dataclass(frozen=True, slots=True)
class Capability:
    """One thing the framework will be able to do, and when."""

    id: str
    what: str
    milestone: str
    area: str
    epic: str
    depends_on: tuple[str, ...]
    #: ⛔ The `Owns` cell VERBATIM, as `epics` read it, and never interpreted
    #: here: what it says about a row's side is `components`' reading (R1).
    owns: str = ""

    def row(self, delivered: str | None) -> str:
        """Render as one row of the index's table, with `delivered` or without it.

        ⛔ `delivered` is passed and never defaulted — `None` is *this table
        has no side column*, which is a decision the index takes over the whole
        population, not one a row may take for itself.
        """
        waits = ", ".join(f"`{name}`" for name in self.depends_on) or "—"
        side = "" if delivered is None else f" {delivered} |"
        return f"| `{self.id}` | {self.what} | {self.area} |{side} {waits} |"


@dataclass(frozen=True, slots=True)
class Epic:
    """One epic document, read as capabilities plus whatever was cancelled."""

    epic: str
    area: str
    capabilities: tuple[Capability, ...]
    cancelled: tuple[str, ...]
    #: Everything before the first task heading, carried so `components` can
    #: read the component an epic's prose rows are delivered inside.
    preamble: str = ""


@dataclass(frozen=True, slots=True)
class Sequence:
    """The order milestones run in, and the bare name of the document declaring it."""

    name: str
    milestones: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class Index:
    """Every capability the framework will have, ordered by when it lands."""

    epics: tuple[Epic, ...]
    sequence: Sequence
    components: Components

    @classmethod
    def of(cls, epics: Iterable[Epic], sequence: Sequence, components: Components) -> Index:
        """Build an index, ⛔ naming EVERY duplicate id and EVERY unplaceable one.

        ⛔ `sequence` is required: an index with no declared order would fall
        back to id order without saying so, which is the defect it removes.
        ⛔ `components` is required for the same kind of reason: an index that
        defaulted to *everything is this framework's* would make the false
        statement the side column exists to stop, and make it silently.

        ⛔ **R6:** the walk gathers and refuses once. Epics carrying
        four misplaced capabilities are refused with four reasons, because
        otherwise the reader learns there were four by running it four times.
        """
        gathered = tuple(epics)
        if not gathered:
            raise IndexRefused("an index of no epics answers every question with silence")
        seen: dict[str, str] = {}
        refusals: list[str] = []
        for epic in gathered:
            for capability in epic.capabilities:
                if capability.id in seen:
                    refusals.append(
                        f"{capability.id} is declared twice — in {seen[capability.id]} "
                        f"and in {epic.epic}"
                    )
                if capability.milestone not in sequence.milestones:
                    refusals.append(
                        f"{capability.id} lands at {capability.milestone}, which "
                        f"{sequence.name} does not declare, so it has no place in the order"
                    )
                seen.setdefault(capability.id, epic.epic)
        if refusals:
            raise IndexRefused(one_or_all(refusals))
        return cls(gathered, sequence, components)

    @property
    def capabilities(self) -> tuple[Capability, ...]:
        """Every capability, in the order the documents declared them."""
        return tuple(c for epic in self.epics for c in epic.capabilities)

    @property
    def cancelled(self) -> tuple[str, ...]:
        """Every row that declares no milestone, counted rather than dropped."""
        return tuple(name for epic in self.epics for name in epic.cancelled)

    @property
    def milestones(self) -> tuple[str, ...]:
        """Every declared milestone, in the declared order — ⛔ empty ones included."""
        return self.sequence.milestones

    @property
    def sides(self) -> dict[str, str]:
        """Each capability id mapped to the side that delivers it — ⛔ a value in `SIDES`."""
        return {
            capability.id: self.components.side(capability.owns, epic.preamble)
            for epic in self.epics
            for capability in epic.capabilities
        }

    @property
    def distinguishes(self) -> bool:
        """Report whether any row is not this framework's, which is when the column is printed."""
        return any(side != HERE for side in self.sides.values())

    def on(self, side: str) -> tuple[Capability, ...]:
        """Every capability delivered on `side`. ⛔ Refuses a value outside `SIDES`."""
        if side not in SIDES:
            raise IndexRefused(f"no such side — the vocabulary is {SIDES}")
        sides = self.sides
        return tuple(c for c in self.capabilities if sides[c.id] == side)

    def milestone_of(self, task: str) -> str:
        """When `task` lands. ⛔ Refuses an id the index does not carry."""
        for capability in self.capabilities:
            if capability.id == task:
                return capability.milestone
        raise IndexRefused(f"no such capability — the index carries {len(self.capabilities)}")

    def _position(self, milestone: str) -> int:
        """Say where `milestone` falls in the declared order, refusing one it omits."""
        if milestone not in self.milestones:
            raise IndexRefused(f"no such milestone — the index knows {self.milestones}")
        return self.milestones.index(milestone)

    def later(self, milestone: str, *, than: str) -> bool:
        """Say whether `milestone` comes strictly after `than` in the declared order.

        ⛔ **The one comparison of milestones in this package.** Anything that
        asks *is this later?* asks here, so no caller can compare ids instead.
        """
        return self._position(milestone) > self._position(than)

    def at(self, milestone: str) -> tuple[Capability, ...]:
        """Every capability delivered at `milestone`, in document order."""
        return tuple(c for c in self.capabilities if c.milestone == milestone)

    def after(self, milestone: str) -> tuple[Capability, ...]:
        """Every capability delivered strictly later than `milestone`.

        ⭐ This is what a corpus that finishes at `milestone` will never use,
        and it is the population a terminal statement has to account for —
        ⛔ **once it has been split by side**, because the ones this framework
        does not deliver are not this corpus's to explain away.
        """
        self._position(milestone)
        return tuple(c for c in self.capabilities if self.later(c.milestone, than=milestone))

    def render(self) -> str:
        """Render the index as a document, byte-identical on every regeneration."""
        column = self.distinguishes
        sides = self.sides
        heading = f"| capability | what it is | area | {SIDE_COLUMN} | waits on |"
        out = [
            "# The capability index",
            "",
            f"**{BANNER}**",
            "",
            "⭐ **What a planner asks the framework, and the only thing it has to "
            "read to find out: *when does capability X become available?***",
            "",
            "⛔ **Derived from the epic documents, never transcribed from them.** "
            "A hand-edit here is a finding against the delivery skill, not "
            "a fix — it is reverted by the next regeneration.",
            "",
            self._derivation(),
            "",
            f"⛔ **Milestones run in the order `{self.sequence.name}` declares, not the "
            f"order their ids sort to:** {' → '.join(f'`{m}`' for m in self.milestones)}.",
            "",
        ]
        if column:
            out += [self._legend(), ""]
        for milestone in self.milestones:
            delivered = self.at(milestone)
            counted = "capability" if len(delivered) == 1 else "capabilities"
            out += [f"## {milestone} — {len(delivered)} {counted}", ""]
            if not delivered:
                out += [EMPTY, ""]
                continue
            out += [
                heading if column else "| capability | what it is | area | waits on |",
                "|---|---|---|---|---|" if column else "|---|---|---|---|",
                *(c.row(sides[c.id] if column else None) for c in delivered),
                "",
            ]
        return "\n".join(out)

    def _legend(self) -> str:
        """Say what the side column's three values mean, since a reader meets them there."""
        return (
            f"⛔ **`{SIDE_COLUMN}` is READ, never judged:** `{HERE}` is a row whose `Owns` "
            f"names a path here; `{ELSEWHERE}` is one whose `Owns` — or whose epic's "
            f"preamble — reaches a component this workspace pins somewhere else; "
            f"`{UNDECLARED}` is a row that names no path at all, so ⚠️ **nothing in the "
            "documents says**. ⛔ A corpus states nothing about the last two."
        )

    def _derivation(self) -> str:
        """Derive the coverage line — ⛔ never a literal somebody typed."""
        dropped = len(self.cancelled)
        empty = sum(1 for milestone in self.milestones if not self.at(milestone))
        counted = (
            f"**{len(self.capabilities)} capabilities · {len(self.epics)} epic documents · "
            f"{len(self.milestones)} milestones, {empty} with no capability · {dropped} "
            f"cancelled {'row' if dropped == 1 else 'rows'} carried and not counted.**"
        )
        if not self.distinguishes:
            return counted
        return (
            f"{counted}\n\n**Of those capabilities, {len(self.on(HERE))} are this "
            f"framework's to deliver, {len(self.on(ELSEWHERE))} are delivered inside a "
            f"component pinned somewhere else, and {len(self.on(UNDECLARED))} declare no "
            "path at all.**"
        )
