"""Mirror of `tools/quality/board/delivery.py` (R12), ⛔ over a SYNTHESISED repository.

⭐ **The fixture carries two waves and every shape the row declares:**

| wave | merge | what it is for |
|---|---|---|
| `wave1` | `Merge feat/SF-01-address (SF-01): …` | a framework delivery |
| `wave1` | `Merge chore/po-round1 (PO round 1): SF-02 …` | ⛔ roll-up false positive (clause 3) |
| `wave1` | `Merge feat/NS-01-service: …` | ⭐ a SIBLING delivery (the annotation's column) |
| `wave1` | the board closes `M0` at the NS-01 merge | the ledger (clause 4), holding `SF-02` |
| `wave2` | `Merge fix/W9-tidy (W9 -- follows SF-02): tidies SF-01's prose` | ⛔ delivers NOTHING |

⭐ **The identity the fixture commits with is a PLACEHOLDER** (R7).
"""

from __future__ import annotations

import inspect
from pathlib import Path

import pytest

import tools.quality as quality
from tests.support import assert_package_contract, repository_root
from tests.support import git as git_binary
from tools.quality.board import delivery
from tools.quality.board.delivery import (
    INDEX,
    READ,
    UNREAD,
    Arm,
    Population,
    Reading,
    delivered_by,
    main,
    population,
    read,
    render,
    sibling_owned,
)
from tools.quality.config import read_text
from tools.workspace import git

RELEASE = "release/m0-foundations"
AUTHOR = ("-c", "user.name=Example Author", "-c", "user.email=author@example.invalid")
BANNER = (
    "# The capability index\n\n**GENERATED by the delivery skill. Do not edit — regenerate.**\n\n"
)
WORKSPACE = (
    '{"workspace_api": 1, "components": ['
    '{"name": "studyforge", "where": "self", "status": "present"},'
    '{"name": "narrate-service", "where": "sibling", "status": "not-yet-created"}]}'
)
README = "### M0 — Foundations\n\n- **0.1** — SF-01, SF-02, NS-01\n\n`NS/` = `narrate-service`.\n"
KNOWN = {"SF-01", "SF-02", "SF-03", "SF-10", "SF-43", "NS-01", "FND-02"}


def index(milestones: dict[str, list[str]], stated: int | None = None, banner: bool = True) -> str:
    """An index in the generator's shape: banner, stated total, one table per milestone."""
    total = sum(len(names) for names in milestones.values())
    text = (
        BANNER if banner else "# A hand-kept list\n\n"
    ) + f"**{stated or total} capabilities · x.**\n\n"
    for milestone, names in milestones.items():
        text += f"## {milestone} — {len(names)} capabilities\n\n"
        text += "| capability | what it is |\n|---|---|\n"
        for name in names:
            what = "⛔ RETIRED 2026-09-12 (was: a thing)" if name == "FND-02" else "a thing"
            text += f"| `{name}` | {what} | area | — |\n"
        text += "\n"
    return text


def task(row: str, owns: str) -> str:
    """One epic entry in the shape the epics write it."""
    declaration = "**Milestone** **M0** · **Depends on** — · **Team** solo"
    return f"### {row} — a row\n{declaration}\n**Owns** {owns}\n\n"


EPICS = {
    "docs/tasks/E01-core.md": "# E01\n\n---\n\n"
    + task("SF-01", "`src/studyforge/a.py`")
    + task("SF-02", "`src/studyforge/b.py`")
    + task("SF-03", "`src/studyforge/c.py`")
    + task("FND-02", "`tools/x.py`"),
    "docs/tasks/E13-narration.md": "# E13\n\nIt becomes **`narrate-service`**.\n\n---\n\n"
    + task("NS-01", "`NS/`"),
}
POPULATION = {"M0": ["SF-01", "SF-02", "NS-01"], "M1": ["SF-03", "FND-02"]}


def board(closes: str) -> str:
    """A board whose milestone table carries `closes`."""
    return (
        "# Board\n\n## Milestones\n\n| Milestone | State | Ref | Record |\n|---|---|---|---|\n"
        + closes
    )


def write(root: Path, files: dict[str, str], message: str) -> str:
    """Write `files`, commit them on the current branch, and return the new sha."""
    for name, text in files.items():
        (root / name).parent.mkdir(parents=True, exist_ok=True)
        (root / name).write_text(text, encoding="utf-8")
        assert git(root, "add", name).returncode == 0
    assert git(root, *AUTHOR, "commit", "-q", "-m", message).returncode == 0
    return git(root, "rev-parse", "HEAD").stdout.strip()


def merge(root: Path, branch: str, subject: str) -> str:
    """Cut `branch`, commit on it, absorb it `--no-ff` under `subject`, return the merge sha."""
    assert git(root, "checkout", "-q", "-b", branch).returncode == 0
    write(root, {f"{branch.replace('/', '-')}.txt": "x\n"}, f"work on {branch}")
    assert git(root, "checkout", "-q", RELEASE).returncode == 0
    assert git(root, *AUTHOR, "merge", "--no-ff", "-q", branch, "-m", subject).returncode == 0
    return git(root, "rev-parse", "HEAD").stdout.strip()


@pytest.fixture
def repository(tmp_path: Path) -> Path:
    """The two waves the module docstring tabulates, tagged `base`, `wave1` and `wave2`."""
    assert git_binary()
    root = tmp_path / "repo"
    root.mkdir()
    assert git(root, "init", "-q", "-b", RELEASE).returncode == 0
    plan = {INDEX: index(POPULATION), "docs/tasks/README.md": README, "workspace.json": WORKSPACE}
    plan["docs/tasks/BOARD.md"] = board("| **M0** — foundations | ⏳ OPEN | — | x |\n")
    write(root, {**plan, **EPICS}, "the plan")
    assert git(root, "tag", "base").returncode == 0
    merge(root, "feat/SF-01-address", "Merge feat/SF-01-address (SF-01): the address model")
    merge(root, "chore/po-round1", "Merge chore/po-round1 (PO round 1): SF-02 ruled ready")
    closed = merge(root, "feat/NS-01-service", "Merge feat/NS-01-service: a sibling stood up")
    row = f"| **M0** — foundations | ✅ CLOSED | `{closed[:7]}` | x |\n"
    write(root, {"docs/tasks/BOARD.md": board(row)}, "close M0")
    assert git(root, "tag", "wave1").returncode == 0
    merge(root, "fix/W9-tidy", "Merge fix/W9-tidy (W9 -- follows SF-02): tidies SF-01's prose")
    assert git(root, "tag", "wave2").returncode == 0
    return root


# Clause 1 — the design decision: a command over two refs, never the floor.


def test_the_module_states_its_contract() -> None:
    """R17: what it does, how you use it, what it depends on."""
    assert_package_contract(delivery, "tools.quality.board.delivery")


def test_the_design_it_is_a_COMMAND_and_never_in_CHECKS_or_NOTICES() -> None:
    """⛔ A commit-graph reading in the floor would change the floor with no file changing."""
    registered = [*quality.CHECKS, *quality.NOTICES]
    assert all(entry.__module__ != delivery.__name__ for entry in registered)


def test_the_reading_is_a_function_of_the_REFS_and_never_the_working_tree(repository: Path) -> None:
    """⭐ The same two refs print the same reading over a dirty tree. Plant: read the disk → RED."""
    before = render(read(repository, "base", "wave1"))
    (repository / INDEX).write_text("# not the index\n", encoding="utf-8")
    (repository / "docs/tasks/BOARD.md").write_text("# no table\n", encoding="utf-8")
    (repository / "workspace.json").unlink()
    assert render(read(repository, "base", "wave1")) == before


# Clause 5 — both directions (R12).


def test_a_wave_that_DELIVERS_prints_a_different_figure_from_one_that_delivers_NONE(
    repository: Path,
) -> None:
    """⭐ `wave1` delivers on both arms and `wave2` on neither, and BOTH exit `READ`."""
    delivering, empty = read(repository, "base", "wave1"), read(repository, "wave1", "wave2")
    assert delivering.subject.in_range == {"SF-01", "NS-01"}
    assert delivering.ledger.in_range == {"SF-01", "SF-02", "NS-01"}
    assert empty.subject.in_range == frozenset() and empty.ledger.in_range == frozenset()
    assert (delivering.exit, empty.exit) == (READ, READ)
    ranged = [line for line in render(empty) if "in this range" in line]
    assert ranged == ["    in this range: framework 0 [] · sibling 0 []"] * 2
    assert not set(ranged) & set(render(delivering))


# Clause 3 — the false-positive class is declared.


def test_a_ROLL_UP_subject_citing_an_id_is_NOT_a_delivery_and_is_PRINTED(repository: Path) -> None:
    """⛔ `SF-02` is named only by a round's roll-up. Plant: count every named id → RED."""
    reading = read(repository, "base", "wave2")
    assert "SF-02" not in reading.subject.through
    assert any(note.startswith("SF-02@") for note in reading.subject.notes)
    assert any("declared NOT a delivery" in line and "SF-02@" in line for line in render(reading))


@pytest.mark.parametrize(
    ("subject", "delivers", "named_only"),
    [
        ("Merge feat/SF-01-address (SF-01): the model", {"SF-01"}, set()),
        ("Merge feat/rebuild-own-output (SF-43): a rebuild", {"SF-43"}, set()),
        ("Merge chore/po-round77 (PO round 77): SF-01 closed", set(), {"SF-01"}),
        ("Merge chore/cto-round42 annotation: SF-03 restated", set(), {"SF-03"}),
        ("Merge chore/cto-round25 (SF-03 approved): landed", set(), {"SF-03"}),
        ("Merge fix/W9-tidy (W9): tidies SF-01's prose", set(), {"SF-01"}),
        ("Merge fix/W250-x (W250 -- unblocks SF-03): a fix", set(), {"SF-03"}),
        ("Merge feat/NS-01-SF-10-pair: two at once", {"NS-01", "SF-10"}, set()),
        ("Merge feat/SF-100-x: an id nobody declared", set(), set()),
        ("Handoff: SF-01 closed", set(), {"SF-01"}),
    ],
)
def test_a_subject_delivers_only_from_its_HEADER(
    subject: str, delivers: set[str], named_only: set[str]
) -> None:
    """⭐ The branch and the `(…)` group before a spaced dash; ⛔ never prose, never a round's."""
    assert delivered_by(subject, KNOWN) == (delivers, named_only)


# Clause 2 — the population is the GENERATED index, at `until`.


def test_the_population_MOVES_with_the_index_at_until(repository: Path) -> None:
    """⭐ A row the generator adds is read at the ref it lands. Plant: a hand-kept list → RED."""
    grown = {**POPULATION, "M1": ["SF-03", "FND-02", "SF-10"]}
    write(repository, {INDEX: index(grown)}, "regenerate the index")
    before, after = read(repository, "base", "wave1"), read(repository, "base", "HEAD")
    assert len(before.population.milestone) == len(POPULATION["M0"] + POPULATION["M1"])
    assert set(after.population.milestone) - set(before.population.milestone) == {"SF-10"}
    assert before.population.retired == {"FND-02"}


@pytest.mark.parametrize(
    ("text", "reason"),
    [
        (None, "no docs/capability-index.md"),
        (index(POPULATION, banner=False), "not the generated index"),
        (index(POPULATION, stated=99), "states 99 capabilities"),
        (BANNER + "**0 capabilities · x.**\n", "yielded no capability row"),
    ],
)
def test_a_population_that_is_not_the_generated_index_is_REFUSED(text, reason: str) -> None:
    """⛔ A hand-kept, truncated or absent population is a reason, never a figure."""
    found = population(text)
    assert isinstance(found, str) and reason in found


def test_an_index_that_is_not_generated_at_until_is_UNREAD(repository: Path) -> None:
    """⛔ The command says so, exits `UNREAD`, and prints no arm."""
    write(repository, {INDEX: index(POPULATION, banner=False)}, "hand-edit the index")
    reading = read(repository, "base", "HEAD")
    assert reading.exit == UNREAD and reading.subject is None and reading.ledger is None
    assert any("NOT READ" in line for line in render(reading))


def test_the_LIVE_index_is_the_generated_population() -> None:
    """⭐ The shipped index parses, and its stated total equals the rows read."""
    found = population(read_text(repository_root() / INDEX))
    assert isinstance(found, Population) and found.milestone


# The annotation's second column: capabilities owned inside a SIBLING component.


def test_a_SIBLING_capability_is_its_OWN_column(repository: Path) -> None:
    """⭐ `NS-01` owns `NS/`. Plant: an empty sibling column → RED."""
    reading = read(repository, "base", "wave1")
    assert reading.siblings == {"NS-01": "narrate-service"}
    assert "    in this range: framework 1 [SF-01] · sibling 1 [NS-01:narrate-service]" in render(
        reading
    )


def test_a_sibling_read_from_the_epic_PREAMBLE_is_still_a_sibling() -> None:
    """⚠️ `W156`'s weak derivation: an `Owns` cell with no code span, its preamble naming one."""
    epics = {"docs/tasks/E13.md": EPICS["docs/tasks/E13-narration.md"] + task("NS-02", "the API")}
    assert sibling_owned(README, WORKSPACE, epics) == {
        "NS-01": "narrate-service",
        "NS-02": "narrate-service",
    }


def test_a_plan_whose_sibling_column_CANNOT_be_read_is_UNREAD_and_not_all_framework(
    repository: Path,
) -> None:
    """⛔ No `workspace.json` at `until` is not *zero siblings*."""
    assert git(repository, "rm", "-q", "workspace.json").returncode == 0
    assert git(repository, *AUTHOR, "commit", "-q", "-m", "drop the pin").returncode == 0
    reading = read(repository, "base", "HEAD")
    assert reading.exit == UNREAD
    assert any("the sibling column" in reason for reason in reading.unread)


# Clause 4 — the milestone ledger is the stronger reading.


def test_the_LEDGER_books_a_milestone_at_its_close_and_the_disagreement_is_PRINTED(
    repository: Path,
) -> None:
    """⭐ `SF-02` is delivered by the ledger alone — `FND-09`'s live shape at `973fc67`."""
    reading = read(repository, "base", "wave2")
    assert reading.ledger.through == {"SF-01", "SF-02", "NS-01"}
    assert "  the readings disagree through" in "\n".join(render(reading))
    assert "ledger only [SF-02] · subjects only []" in "\n".join(render(reading))


def test_a_close_at_NO_named_ref_counts_through_until_and_never_in_a_range(
    repository: Path,
) -> None:
    """⚠️ Declared: `M0`'s live row reads `—`; an unresolvable ref is printed, never ranged."""
    rows = "| **M0** — f | ✅ CLOSED | — | x |\n| **M1** — g | ✅ CLOSED | `abcdef1` | x |\n"
    write(repository, {"docs/tasks/BOARD.md": board(rows)}, "close with no ref")
    reading = read(repository, "base", "HEAD")
    assert reading.ledger.in_range == frozenset()
    assert reading.ledger.through == {"SF-01", "SF-02", "NS-01", "SF-03", "FND-02"}
    assert any("no named ref" in note for note in reading.ledger.notes)
    assert any("does not resolve" in note for note in reading.ledger.notes)


def test_a_board_with_NO_milestone_table_is_UNREAD(repository: Path) -> None:
    """⛔ Ruling 191: an absent ledger is not an empty one."""
    write(repository, {"docs/tasks/BOARD.md": "# Board\n"}, "drop the table")
    reading = read(repository, "base", "HEAD")
    assert reading.exit == UNREAD and reading.ledger is None and reading.subject is not None


def test_a_ref_that_does_not_resolve_is_UNREAD(repository: Path) -> None:
    """⛔ git declining to answer is never a range with nothing in it."""
    reading = read(repository, "no-such-ref", "wave1")
    assert reading.exit == UNREAD and reading.population is None


# ⛔ MUST NOT: a quota, a target or a gate.


def test_MUST_NOT_no_figure_moves_the_exit(repository: Path) -> None:
    """⛔ A zero figure reads `READ`, and the exit is a function of `unread` alone."""
    assert read(repository, "wave1", "wave2").exit == READ
    nothing = Arm(frozenset(), frozenset(), ())
    empty = Reading("a", "b", Population({}, frozenset()), {}, nothing, nothing, ())
    assert empty.exit == READ
    assert {READ, UNREAD} == {0, 2}
    assert "return 1" not in inspect.getsource(delivery)


def test_the_command_line_prints_the_population_BEFORE_either_arm(
    repository: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """⭐ The entry point a wave's close runs, asserted rather than assumed (Ruling 128)."""
    code = main(["--root", str(repository), "wave1", "wave2"])
    printed = capsys.readouterr().out
    assert code == READ
    assert printed.index("population:") < printed.index("ledger (") < printed.index("merge subj")
    assert str(repository) not in printed, "⛔ R7: no absolute path in a reading"
