"""Mirror of `tools/quality/rulings/document.py` (R12).

⛔ **The header's numbers are the claim this task stands on**, so they are
asserted against the derivation rather than against themselves: the count in the
prose is the same object as the number of rows, measured twice and compared.
⭐ That is what *derived, not typed* has to mean to be worth saying (Ruling 192's
subject, from the other side).
"""

from __future__ import annotations

from tests.support import repository_root
from tools.quality.rulings.derive import entries
from tools.quality.rulings.document import link, text
from tools.tests.quality.rulings.support import ROUND_14, tree


def rows(document: str) -> list[str]:
    """Every table row of a rendered index — the lines that start a numbered cell."""
    return [line for line in document.splitlines() if line.startswith("| ") and "](" in line]


def test_the_link_is_relative_to_the_index_not_to_the_root():
    """⚠️ A link resolves against its own document's directory, and so does the checker."""
    assert link("docs/tasks/handoffs/CTO-2026-09-10-round50.md") == (
        "handoffs/CTO-2026-09-10-round50.md"
    )


def test_there_is_exactly_one_row_per_derived_ruling(tmp_path):
    """The rendered table is the derivation, with nothing added and nothing lost."""
    tree(tmp_path, r14=ROUND_14)
    document = text(tmp_path)
    assert len(rows(document)) == len(entries(tmp_path)) == 2


def test_the_header_count_is_the_row_count_on_the_live_tree():
    """⛔ The completeness claim, compared with itself rather than asserted."""
    root = repository_root()
    document = text(root)
    derived = len(entries(root))
    assert f"**{derived} rulings, `1`–`{derived}`" in document
    assert len(rows(document)) == derived


def test_a_number_outside_the_series_is_named_in_the_header(tmp_path):
    """⛔ Printed rather than dropped: the probe number is reported as excluded."""
    tree(
        tmp_path,
        r14=ROUND_14,
        r15="# CTO — round 15\n\n## ⛔ Ruling 9999 — an impossible control\n",
    )
    document = text(tmp_path)
    assert "OUTSIDE the contiguous series" in document
    assert "`9999`" in document
    assert len(rows(document)) == 2


def test_a_contiguous_series_says_so_instead(tmp_path):
    """The reading that must differ: no excluded number, a different sentence."""
    tree(tmp_path, r14=ROUND_14)
    document = text(tmp_path)
    assert "OUTSIDE the contiguous series" not in document
    assert "contiguous and nothing was written outside it" in document


def test_the_document_declares_that_it_is_generated(tmp_path):
    """R19: a hand-edit here is a finding, and the document has to say so itself."""
    tree(tmp_path, r14=ROUND_14)
    document = text(tmp_path)
    assert document.startswith("# The rulings index")
    assert "GENERATED by `python3 -m tools.quality.rulings`" in document
    assert "Do not edit — regenerate" in document


def test_the_document_separates_the_two_ruling_series(tmp_path):
    """⛔ `R1`–`R21` are the spec's and are never merged into this table."""
    tree(tmp_path, r14=ROUND_14)
    assert "are the SPEC's rulings and are a different series" in text(tmp_path)
