r"""What a runnable corpus gets, and what a corpus that is not gets: nothing.

**What it does.** Joins one corpus's manifest with the pinned components'
contracts and produces the compose file, the toolchain selection, the prime and
the reader's document — or, for a corpus that declares no runtime, an empty
result and no error.

**How you use it.** `generate(manifest, …)` returns an `Execution`;
`write(execution, root)` puts it on disk; `NOT_MATERIAL` and `classified` are
what a manifest declares about it.

**Depends on.** `composefile`, `prime`, `toolchain`, `contract`, and the
manifest's own reader. ⛔ Nothing source-specific (R1).

## ⛔ A CORPUS THAT DECLARES NO RUNTIME GETS NOTHING FROM HERE, AND NO ERROR

⭐ **`manifest.runtimes` is the whole test.** An absent key is `()` — no runner,
no editor, no prime — and §7's C5 says such a corpus is **complete at the
reading floor**, not short of something.

⛔ **So the result is empty: no path, no file, no warning, no stub.** A
generator that emitted a broken compose file rather than say *"your corpus
never asked for one"* would be the theatre R5 forbids, and it would put a
Docker dependency in front of somebody converting a book (spec §11.0).

## ⭐ WHICH DIRECTORY IS BOUND IS DERIVED, AND THE DERIVATION IS THE RULING

⚠️ **§8.1 ruling 2: only the sources are mounted — not the repository.** The
manifest carries no key naming the directory an editor binds, so it is derived
from `content.include`'s own common root, which is the corpus's own statement
about where its material lives.

⛔ **A corpus whose material is at the repository root is REFUSED**, because
there is then no directory to bind that is not the repository. ⚠️ **`SK-09/5`:
the remedy is a manifest key, and it is a finding rather than a default written
in here** (R19).

## ⛔ RE-RUNNING CHANGES NOTHING

⭐ The same manifest and the same contracts render the same bytes, and `write`
is therefore idempotent. ⛔ **A hand-edit to any file this writes is a finding
against this skill, not a fix**: it is reverted on the next run, and a tool that
eats your changes is a tool nobody runs twice.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

from studyforge.corpus.manifest import Manifest
from studyforge.skills.execution import composefile, contract, toolchain
from studyforge.skills.execution.prime import Prime, PrimeRefused, prime_for

#: Where everything this skill generates lives. ⭐ Under the corpus's own
#: bookkeeping directory, never beside its material: every byte here is
#: generated and R3 keeps the corpus's own files untouched.
DIRECTORY = ".studyforge/execution"

#: The compose file a reader brings up.
COMPOSE_FILE = f"{DIRECTORY}/compose.yaml"

#: The selection a corpus keeps: the set, what is carried, and the two argv.
TOOLCHAIN_FILE = f"{DIRECTORY}/toolchain.json"

#: The prime the build is handed: `<tool>/` per project (`W440`).
PRIME_DIR = f"{DIRECTORY}/prime"

#: The slot `runner.prime.declared_by` leaves for the directory.
DIRECTORY_SLOT = "<directory>"

#: What a reader opens first.
READER_DOC = "EXECUTION.md"

#: ⛔ The sentence every generated document carries, so a file nobody may edit
#: says so itself. ⚠️ `write` refuses a reader's document that does not carry
#: it, which is how a hand-written one is never silently overwritten.
GENERATED = (
    "⛔ Generated by studyforge execution onboarding. A hand-edit here is a "
    "finding against that skill rather than a fix (R19); change corpus.json "
    "and regenerate."
)

#: Why none of this is material. ⚠️ Long enough to clear the manifest's own
#: minimum, because a reason the document refuses is a reason the integrator
#: has to invent — which is the retyping R19 forbids.
WHY_DIRECTORY = (
    "the compose file, the toolchain selection and the prime project this "
    "corpus's execution onboarding generated: how its material is run, never "
    "material it teaches."
)
WHY_READER = (
    "the execution report, written from this corpus's own declarations and "
    "from the pinned components' contracts, and regenerated rather than edited."
)

#: Every glob this skill's own output needs, with the reason each one gives.
NOT_MATERIAL = (
    {"glob": f"{DIRECTORY}/**", "why": WHY_DIRECTORY},
    {"glob": READER_DOC, "why": WHY_READER},
)

#: Characters that make a path component a pattern rather than a directory.
GLOB_CHARACTERS = "*?[]"


class ExecutionRefused(ValueError):
    """A corpus this skill will not generate execution artifacts for, and why."""


@dataclass(frozen=True, slots=True)
class Execution:
    """Everything a runnable corpus gets — or, for one that is not, nothing."""

    runnable: bool
    #: `(path, text)` for each generated document, in the order they are written.
    files: tuple[tuple[str, str], ...] = ()
    #: `(generated path, corpus-relative path)` for each file the prime copies.
    copies: tuple[tuple[str, str], ...] = ()
    selection: toolchain.Selection | None = None
    primed: Prime | None = None

    def paths(self) -> tuple[str, ...]:
        """Every path this skill occupies, in the order it writes them."""
        return tuple([where for where, _ in self.files] + [where for where, _ in self.copies])


def source_root(manifest: Manifest) -> str:
    """Return the directory an editor binds, from `content.include` (ruling 2)."""
    roots = [_root_of(one) for one in manifest.content.include]
    if not roots or not all(roots):
        raise ExecutionRefused(
            "this corpus's content.include names the repository root, so §8.1 ruling 2 "
            "leaves no directory to mount: only the sources are mounted, never the "
            "repository. Declare material under a directory, or add a manifest key that "
            "names the one an editor binds"
        )
    shared = PurePosixPath(roots[0])
    for one in roots[1:]:
        shared = _common(shared, PurePosixPath(one))
    if not shared.parts:
        raise ExecutionRefused(
            "this corpus's content.include globs share no directory, so §8.1 ruling 2 "
            "would mount the repository to reach them all. Declare them under one "
            "directory, or add a manifest key that names the one an editor binds"
        )
    return shared.as_posix()


def generate(
    manifest: Manifest,
    *,
    editor_text: str,
    root: Path,
    narration_text: str | None = None,
    project: str | None = None,
) -> Execution:
    """Everything a runnable corpus gets, from manifest data and contracts alone."""
    if not manifest.runtimes:
        return Execution(runnable=False)
    editor = contract.read(
        editor_text,
        component=contract.EDITOR_COMPONENT,
        api=contract.EDITOR_API,
        promise=contract.EDITOR_PROMISE,
    )
    block = contract.require(editor, "editor")
    if not isinstance(block, Mapping):
        raise contract.ContractRefused("the contract's editor must be an object")
    selection = toolchain.select(manifest.runtimes, editor)
    sources = source_root(manifest)
    # ⭐ The prime is selected for what the image will CARRY, not for everything
    # the corpus declared: an image without a runtime cannot compile a specimen
    # in it, and the withheld ones are named in the reader's document instead.
    seeds = contract.optional(editor, "runner", "prime", "seeds", default={})
    seeded = tuple(seeds) if isinstance(seeds, Mapping) else ()
    primed = _primed(root, selection.carried, seeded)
    flag = _prime_flag(editor) if primed.projects else None
    compose = composefile.render(
        project=project or f"studyforge-{manifest.source}",
        editor=block,
        image=selection.image_value,
        sources=_from_compose(sources),
        runtimes=manifest.runtimes,
        seeds=seeds if isinstance(seeds, Mapping) else None,
        checked=_checked(narration_text),
    )
    return Execution(
        runnable=True,
        files=(
            (COMPOSE_FILE, compose),
            (TOOLCHAIN_FILE, selection.render()),
            (
                READER_DOC,
                _reader(manifest, selection, primed, block, sources, narration_text, seeds, flag),
            ),
        ),
        copies=tuple((f"{PRIME_DIR}/{inside}", origin) for inside, origin in primed.copies()),
        selection=selection,
        primed=primed,
    )


def write(execution: Execution, root: Path) -> tuple[str, ...]:
    """Write everything, and return what was written. ⭐ Re-running changes nothing."""
    written = []
    for where, text in execution.files:
        target = root / where
        if where == READER_DOC and _is_somebody_elses(target):
            raise ExecutionRefused(
                "this corpus already carries a reader's document that this skill did not "
                "write, and R3 keeps an existing file untouched. Move it aside, or say so "
                "and regenerate"
            )
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
        written.append(where)
    for where, origin in execution.copies:
        target = root / where
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes((root / origin).read_bytes())
        written.append(where)
    return tuple(written)


def _is_somebody_elses(target: Path) -> bool:
    """Whether a reader's document already there is one this skill did not write."""
    return target.is_file() and GENERATED not in target.read_text(encoding="utf-8")


def classified(where: str, entries: Sequence[Mapping[str, str]] = NOT_MATERIAL) -> bool:
    """Whether one path is covered by a glob this module declares."""
    candidate = PurePosixPath(where)
    return any(candidate.full_match(entry["glob"]) for entry in entries)


def _checked(narration_text: str | None) -> tuple[tuple[str, Mapping[str, object]], ...]:
    """Return the narration block, whose rulings are asserted and never rendered."""
    if narration_text is None:
        return ()
    document = contract.read(
        narration_text,
        component=contract.NARRATION_COMPONENT,
        api=contract.NARRATION_API,
        promise=contract.NARRATION_PROMISE,
    )
    block = contract.require(document, "service")
    if not isinstance(block, Mapping):
        raise contract.ContractRefused("the contract's service must be an object")
    return ((contract.NARRATION_COMPONENT, block),)


def _primed(root: Path, runtimes: Sequence[str], seeded: Sequence[str]) -> Prime:
    """Select the prime, with the seeded set from the contract's own prime map."""
    try:
        return prime_for(root, runtimes, seeded=seeded)
    except PrimeRefused as refusal:
        raise ExecutionRefused(str(refusal)) from None


def _prime_flag(editor: Mapping[str, object]) -> str:
    """Return the contract's own prime flag, with this corpus's directory in its slot."""
    flag = contract.require(editor, "runner", "prime", "declared_by")
    if not isinstance(flag, str) or DIRECTORY_SLOT not in flag:
        raise contract.ContractRefused(f"runner.prime.declared_by has no {DIRECTORY_SLOT} slot")
    return flag.replace(DIRECTORY_SLOT, f"<this corpus>/{PRIME_DIR}")


def _from_compose(sources: str) -> str:
    """Return `sources` as the compose file at `COMPOSE_FILE` reaches it."""
    return "/".join([".."] * len(PurePosixPath(DIRECTORY).parts) + [sources])


def _root_of(pattern: str) -> str:
    """Return one include glob's directory prefix, up to its first pattern part.

    ⚠️ A glob with no pattern part names a FILE, so its directory is what is
    taken — a corpus that includes one file by name has still said where its
    material lives.
    """
    kept: list[str] = []
    for part in PurePosixPath(pattern).parts:
        if any(one in part for one in GLOB_CHARACTERS):
            return "/".join(kept)
        kept.append(part)
    return "/".join(kept[:-1])


def _common(first: PurePosixPath, second: PurePosixPath) -> PurePosixPath:
    """Return the longest directory both paths share."""
    shared = []
    for one, other in zip(first.parts, second.parts, strict=False):
        if one != other:
            break
        shared.append(one)
    return PurePosixPath(*shared)


def _reader(
    manifest: Manifest,
    selection: toolchain.Selection,
    primed: Prime,
    block: Mapping[str, object],
    sources: str,
    narration_text: str | None,
    seeds: object,
    flag: str | None,
) -> str:
    """Write the document a reader opens first, from declarations alone."""
    volumes = composefile.volumes_for(
        seeds if isinstance(seeds, Mapping) else None, manifest.runtimes
    )
    lines = [
        f"# Execution — {manifest.title}",
        "",
        GENERATED,
        "",
        "## What this corpus declared",
        "",
        f"- runtimes: `{'`, `'.join(selection.declared)}`",
        f"- the directory the editor binds: `{sources}` (§8.1 ruling 2)",
        f"- the image the component builds: `{selection.image_env}`",
        "",
        "## Build the image",
        "",
        "```",
        " ".join(selection.build),
        " ".join(selection.tag_from),
        "```",
        "",
        "⛔ Never pin a tag you did not compute: a tag is a function of the build's",
        f"inputs. Read the set back from `{selection.read_back_from}`.",
        "",
        "## Bring it up",
        "",
        "```",
        f"docker compose -f {COMPOSE_FILE} up -d --wait",
        "```",
        "",
    ]
    # ⚠️ Corpus-relative here and compose-relative in the file itself: this
    # document sits at the corpus root and that one two directories down, and a
    # path a reader cannot act on from where they are reading is not a remedy.
    first = composefile.must_exist_first(block, volumes, sources)
    if first:
        lines += [
            "⛔ §8.1 ruling 4 — these exist on the host before the start, or docker",
            "creates them root-owned and the container can never write them:",
            "",
            *(f"- `{one}`" for one in first),
            "",
        ]
    if selection.withheld:
        lines += [
            "## What this editor does not carry",
            "",
            *(f"- `{name}` — {why}" for name, why in selection.withheld),
            "",
        ]
    lines += ["## The prime", ""]
    if flag is None:
        lines += ["No runtime this corpus declares is seeded from a build: no prime.", ""]
    else:
        lines += [
            "⛔ An empty prime primes nothing while appearing to succeed. These are this",
            "corpus's own files, one project per seeded tool, copied and never authored:",
            "",
            *(f"- `{inside}` ← `{origin}`" for inside, origin in primed.copies()),
            "",
            f"Pass `{flag}` to the build above.",
            "",
        ]
    if narration_text is not None:
        lines += _narration(narration_text)
    return "\n".join(lines)


def _narration(narration_text: str) -> list[str]:
    """Where narration comes from — by pointer, never by copying its API."""
    document = contract.read(
        narration_text,
        component=contract.NARRATION_COMPONENT,
        api=contract.NARRATION_API,
        promise=contract.NARRATION_PROMISE,
    )
    default = contract.require(document, "profiles", "default")
    files = contract.words(document, "profiles", str(default), "compose_files")
    return [
        "## Narration",
        "",
        f"⛔ Not rendered into this compose file. `{contract.NARRATION_COMPONENT}` is",
        "brought up from its own checkout, by its own compose files:",
        "",
        *(f"- `{one}`" for one in files),
        "",
        "⚠️ Its contract declares no per-project keys, so a consumer cannot render it",
        "without inventing a host port and a volume name (`SK-09/2`).",
        "",
    ]
