"""`W154`: capability delivery between two named refs, printed as a READING that is never a gate.

**What it does.** Reads, at two refs, which capabilities of the GENERATED
`docs/capability-index.md` were delivered in the range between them. It gives two readings.
The first is the MILESTONE LEDGER, the stronger one: `BOARD.md`'s `## Milestones` table, where a
milestone closes at a named ref (Ruling 97). The second is the MERGE-SUBJECT reading, the weaker
one: a capability id in the HEADER of a first-parent merge. Both readings are split into two
columns: capabilities owned in this tree, and capabilities owned inside a SIBLING component
(`E12`/`E13` and the corpus rows, which deliver no bytes into `src/`). Every id the two readings
disagree on is printed.

**How you use it.** Run it at a wave's close, over the wave's two refs:

    python3 -m tools.quality.board.delivery <since> [<until>]    # until defaults to HEAD

`read(root, since, until)` returns the `Reading` the command renders. Exit `0` means both
readings were taken, WHATEVER the figures are. Exit `2` means one of them could not be taken: a
ref that does not resolve, an index that is absent, not generated, or disagrees with its own
stated total, a plan whose sibling column cannot be read, or a board with no milestone table.

**Depends on.** `argparse`, `re`, `sys`, `dataclasses` and `pathlib`; `tools.workspace.git` for
the refs; `creators` for the `Owns` grammar (`W156`); `unclaimed.OFFICE` for a round's branch;
`markdown.code_spans`.

## ⭐ THE DESIGN DECISION (clause 1): a command in `tools/quality/board/`, never the floor

⛔ **Not a floor notice.** The floor is a function of the TREE: it runs over checkouts that are
not repositories, and every notice prints the same line for the same bytes. A reading of the
commit graph changes when HEAD moves with no file changing, so it would be the first floor line
two offices could print differently over identical trees.
⛔ **Not a wave-close step in prose alone.** A procedure with no instrument is the fourth manual
derivation of the figure this row was minted to stop.
⭐ **So it is a command whose inputs are two refs, and it prints both resolved.** It reads only
git objects at those refs and never the working tree, so the same two refs give the same
reading on any checkout, and the reading carries its own refs.

## ⚠️ DECIDED, AND DECLARED (Ruling 292)

⭐ **Decided:**

- the POPULATION is every row of the index at `until`, its `⛔ RETIRED` rows printed apart;
- a SIBLING capability is a row whose `Owns` reaches a `workspace.json` component that is not
  `self`, read with `W156`'s grammar at `until`, its epic preamble included;
- a subject DELIVERS an id named in its header, `Merge <branch>` and a `(…)` group directly
  after it, when the branch is not an office round's. The group is cut at a spaced dash;
- a ledger DELIVERS every capability of a milestone its table reads `✅ CLOSED`. The milestone
  lands in the range when its close ref is in `since..until`.

⚠️ **Declared false positives (clause 3):** an id in a subject's prose; an id anywhere in an
office round's roll-up subject (`chore/po-round<n>`, a suffix included); an id after a spaced
dash inside the header's group. Each is printed as NOT a delivery.
⚠️ **Declared, not decided:** a close ref typed `—` counts through `until` and never in a range;
a close recorded on the board after `until` is not seen; a fast-forward leaves no subject.

## ⛔ WHAT IT MUST NOT BECOME (the row)

⛔ **A quota, a target or a gate.** No figure moves the exit, and no code path returns `1`. A
wave spent on one large capability reads low and is exactly what this project wants.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

from tools.quality.board.unclaimed import OFFICE
from tools.quality.creators import (
    SEQUENCE,
    TASKS_DIR,
    WORKSPACE,
    aliases,
    components,
    preamble_component,
    resolve,
    rows,
)
from tools.quality.markdown import code_spans
from tools.workspace import git

INDEX = "docs/capability-index.md"
BOARD = f"{TASKS_DIR}/BOARD.md"
BANNER = "**GENERATED by the delivery skill."
RETIRED = "⛔ RETIRED"

#: Exit codes: `0` both readings taken, `2` one could not be. ⛔ There is no `1`.
READ, UNREAD = 0, 2

_SECTION = re.compile(r"^## (M[0-9]+) ")
_INDEX_ROW = re.compile(r"^\| `([A-Z]{2,4}-[0-9]{1,3}[a-z]?)` \| ([^|]*)\|")
_STATED = re.compile(r"^\*\*([0-9]+) capabilities\b", re.MULTILINE)
_CLOSED = re.compile(r"^\| \*\*(M[0-9]+)\*\* — [^|]*\| ✅ CLOSED \| (?:`([0-9a-f]{7,40})`|—) \|")
_MILESTONES = re.compile(r"^## Milestones\s*$", re.MULTILINE)
_HEADER = re.compile(r"^Merge\s+([^\s:(]+):?(?:\s+\(([^)]*)\))?")
_SPACED_DASH = re.compile(r"\s+(?:--|—|–)\s+")
_ID = re.compile(r"(?<![A-Za-z0-9])([A-Z]{2,4}-[0-9]{1,3}[a-z]?)(?![A-Za-z0-9])")


@dataclass(frozen=True)
class Population:
    """The generated index at one ref: each capability's milestone, and the retired ones."""

    milestone: dict[str, str]
    retired: frozenset[str]


@dataclass(frozen=True)
class Arm:
    """One reading: ids delivered through `until`, ids in the range, and what it declared."""

    through: frozenset[str]
    in_range: frozenset[str]
    notes: tuple[str, ...]


@dataclass(frozen=True)
class Reading:
    """Everything the command prints. `unread` names each arm that could not be taken."""

    since: str
    until: str
    population: Population | None
    siblings: dict[str, str]
    ledger: Arm | None
    subject: Arm | None
    unread: tuple[str, ...]

    @property
    def exit(self) -> int:
        """Return `READ` or `UNREAD`. ⛔ A figure never reaches this, only an arm's absence."""
        return UNREAD if self.unread else READ


def population(text: str | None) -> Population | str:
    """Return the index's population, or the reason it is not the generated index."""
    if text is None:
        return f"no {INDEX} at this ref"
    if BANNER not in text:
        return f"{INDEX} does not carry the generator's banner, so it is not the generated index"
    milestone: dict[str, str] = {}
    retired: set[str] = set()
    section = ""
    for line in text.splitlines():
        heading = _SECTION.match(line)
        section = heading.group(1) if heading else section
        row = _INDEX_ROW.match(line)
        if row and section:
            milestone[row.group(1)] = section
            if RETIRED in row.group(2):
                retired.add(row.group(1))
    stated = _STATED.search(text)
    if not milestone:
        return f"{INDEX} yielded no capability row"
    if stated is None or int(stated.group(1)) != len(milestone):
        told = stated.group(1) if stated else "no"
        return f"{INDEX} states {told} capabilities and {len(milestone)} rows were read"
    return Population(milestone, frozenset(retired))


def sibling_owned(sequence: str, workspace: str, epics: dict[str, str]) -> dict[str, str]:
    """Each capability whose `Owns` reaches a sibling component, mapped to that component."""
    names = set(components(workspace))
    shorthand = aliases(sequence, names)
    owned: dict[str, str] = {}
    for document, text in sorted(epics.items()):
        fallback = preamble_component(text, names)
        for row in rows(document, text):
            reached = resolve(row.owns, shorthand, names)
            if not reached and not code_spans(row.owns) and fallback is not None:
                reached = {fallback: False}
            if reached:
                owned[row.id] = sorted(reached)[0]
    return owned


def delivered_by(subject: str, known: set[str]) -> tuple[set[str], set[str]]:
    """Return the ids `subject` delivers, and the known ids it names without delivering."""
    named = set(_ID.findall(subject)) & known
    header = _HEADER.match(subject)
    if header is None or OFFICE.match(header.group(1)):
        return set(), named
    group = _SPACED_DASH.split(header.group(2) or "", maxsplit=1)[0]
    delivers = set(_ID.findall(f"{header.group(1)} {group}")) & known
    return delivers, named - delivers


def subject_arm(merges: list[tuple[str, str]], in_range: set[str], known: set[str]) -> Arm:
    """Read first-parent merges, OLDEST first: an id is delivered at the first merge naming it."""
    first: dict[str, str] = {}
    mentioned: dict[str, str] = {}
    for sha, subject in merges:
        delivers, named = delivered_by(subject, known)
        for name in delivers:
            first.setdefault(name, sha)
        for name in named:
            mentioned.setdefault(name, sha)
    prose = sorted(set(mentioned) - set(first))
    notes = tuple(f"{name}@{mentioned[name][:7]}" for name in prose)
    reached = frozenset(name for name, sha in first.items() if sha in in_range)
    return Arm(frozenset(first), reached, notes)


def ledger_arm(board: str | None, found: Population, graph: _Graph) -> Arm | str:
    """Read the board's milestone table: a CLOSED milestone delivers its capabilities."""
    if board is None or not _MILESTONES.search(board):
        return f"no `## Milestones` table in {BOARD} at this ref"
    closed = [match.groups() for match in map(_CLOSED.match, board.splitlines()) if match]
    through: set[str] = set()
    reached: set[str] = set()
    notes: list[str] = []
    for milestone, ref in closed:
        members = {name for name, where in found.milestone.items() if where == milestone}
        through |= members
        sha = graph.resolve(ref) if ref else None
        if sha is not None and sha in graph.in_range:
            reached |= members
            notes.append(f"{milestone} closed at {ref} in this range")
        elif ref is None:
            notes.append(f"{milestone} closed at no named ref, so never in a range")
        elif sha is None:
            notes.append(f"{milestone}'s close ref {ref} does not resolve, so never in a range")
    return Arm(frozenset(through), frozenset(reached), tuple(notes))


class _Graph:
    """The two refs, and every git object the reading takes. ⛔ Never the working tree."""

    def __init__(self, root: Path, since: str, until: str) -> None:
        self.root = root
        self.since = self.resolve(since)
        self.until = self.resolve(until)
        answer = git(root, "rev-list", f"{self.since}..{self.until}") if self.ready else None
        self.in_range = set(answer.stdout.split()) if answer and answer.returncode == 0 else set()

    @property
    def ready(self) -> bool:
        """Report whether both refs resolved to a commit."""
        return self.since is not None and self.until is not None

    def resolve(self, ref: str) -> str | None:
        """Return the full sha `ref` names, or None."""
        answer = git(self.root, "rev-parse", "--verify", "--quiet", f"{ref}^{{commit}}")
        return answer.stdout.strip() if answer.returncode == 0 else None

    def show(self, path: str) -> str | None:
        """Return `path` as it is at `until`, or None."""
        answer = git(self.root, "show", f"{self.until}:{path}")
        return answer.stdout if answer.returncode == 0 else None

    def epics(self) -> dict[str, str]:
        """Every epic document at `until`, by path."""
        answer = git(self.root, "ls-tree", "--name-only", self.until or "", f"{TASKS_DIR}/")
        names = [line for line in answer.stdout.split() if re.search(r"/E[0-9][^/]*\.md$", line)]
        return {name: self.show(name) or "" for name in sorted(names)}

    def merges(self) -> list[tuple[str, str]]:
        """Every first-parent merge of `until`, oldest first, as `(sha, subject)`."""
        answer = git(
            self.root,
            "log",
            "--first-parent",
            "--merges",
            "--reverse",
            "--format=%H%x09%s",
            self.until or "",
        )
        pairs = (line.split("\t", 1) for line in answer.stdout.splitlines() if "\t" in line)
        return [(sha, subject) for sha, subject in pairs]


def read(root: Path, since: str, until: str = "HEAD") -> Reading:
    """Take both readings between `since` and `until`, naming each arm that could not be taken."""
    graph = _Graph(root, since, until)
    shas = (graph.since or since, graph.until or until)
    if not graph.ready:
        return Reading(*shas, None, {}, None, None, (f"a ref does not resolve: {since}..{until}",))
    found = population(graph.show(INDEX))
    if isinstance(found, str):
        return Reading(*shas, None, {}, None, None, (found,))
    unread: list[str] = []
    sequence, workspace = graph.show(SEQUENCE), graph.show(WORKSPACE)
    siblings: dict[str, str] = {}
    if sequence is None or workspace is None or not components(workspace):
        unread.append(f"the sibling column: no {SEQUENCE} or no component in {WORKSPACE}")
    else:
        siblings = sibling_owned(sequence, workspace, graph.epics())
    ledger = ledger_arm(graph.show(BOARD), found, graph)
    if isinstance(ledger, str):
        unread.append(ledger)
        ledger = None
    known = set(found.milestone)
    subject = subject_arm(graph.merges(), graph.in_range, known)
    return Reading(*shas, found, siblings, ledger, subject, tuple(unread))


def _columns(ids: frozenset[str], siblings: dict[str, str]) -> str:
    """`framework <n> [ids] · sibling <n> [ids]`, each column sorted."""
    sibling = sorted(name for name in ids if name in siblings)
    framework = sorted(name for name in ids if name not in siblings)
    return (
        f"framework {len(framework)} [{' '.join(framework)}] · "
        f"sibling {len(sibling)} [{' '.join(f'{n}:{siblings[n]}' for n in sibling)}]"
    )


def render(reading: Reading) -> list[str]:
    """Return the lines the command prints: refs and population first, then each arm."""
    lines = [
        "capability delivery (W154): a READING, never a gate -- no figure moves the exit",
        f"  range: {reading.since[:7]}..{reading.until[:7]}",
    ]
    found = reading.population
    if found is not None:
        retired = sorted(found.retired)
        lines.append(
            f"  population: {len(found.milestone)} capabilities in {INDEX} at "
            f"{reading.until[:7]}, {len(retired)} retired [{' '.join(retired)}]; "
            f"{sum(1 for name in found.milestone if name in reading.siblings)} owned inside a "
            "sibling component"
        )
    for label, arm in (
        ("ledger (the STRONGER reading, Ruling 97)", reading.ledger),
        ("merge subjects (the WEAKER reading, a header grep)", reading.subject),
    ):
        if arm is None:
            continue
        lines.append(f"  {label}:")
        lines.append(f"    in this range: {_columns(arm.in_range, reading.siblings)}")
        lines.append(f"    through {reading.until[:7]}: {_columns(arm.through, reading.siblings)}")
        prefix = (
            "declared NOT a delivery, named only in prose or a roll-up"
            if arm is reading.subject
            else "close"
        )
        lines.extend(f"    {prefix}: {note}" for note in arm.notes)
    if reading.ledger is not None and reading.subject is not None:
        only_ledger = sorted(reading.ledger.through - reading.subject.through)
        only_subject = sorted(reading.subject.through - reading.ledger.through)
        lines.append(
            f"  the readings disagree through {reading.until[:7]}: ledger only "
            f"[{' '.join(only_ledger)}] · subjects only [{' '.join(only_subject)}]"
        )
    lines.extend(f"  ⛔ NOT READ: {reason} (exit {UNREAD})" for reason in reading.unread)
    return lines


def main(argv: list[str] | None = None) -> int:
    """Print the reading between two refs and return `READ` or `UNREAD`, never a verdict."""
    parser = argparse.ArgumentParser(
        prog="python3 -m tools.quality.board.delivery",
        description="Print capability delivery between two refs (W154). Never a gate.",
    )
    parser.add_argument("since", help="the ref the range starts after")
    parser.add_argument("until", nargs="?", default="HEAD", help="the ref it ends at")
    parser.add_argument("--root", type=Path, default=Path("."), help="the repository")
    arguments = parser.parse_args(argv)
    reading = read(arguments.root, arguments.since, arguments.until)
    print("\n".join(render(reading)))
    return reading.exit


if __name__ == "__main__":  # pragma: no cover - the CLI's one line
    sys.exit(main())
