r"""Assemble one generated Python module: its contract, its imports, its checks.

**What it does.** `module(...)` returns the text of a module that states what
it is, says it is generated, and carries the body it was given.

**How you use it.** Called by the renderers in this package; never directly by
a skill's reader.

**Depends on.** The standard library. ⛔ No I/O, and nothing source-specific
(R1).

## ⭐ Composed, never pasted

⚠️ **A contract inside one long string literal is a contract no rule reaches**,
and nothing lints a module that does not exist yet. `SK-02`'s `parts.compose`
made the same argument for a generated adapter and **raises** when a piece is
missing; this is its twin for the two modules an onboarding generates.

⛔ **Every module it composes says it is generated, in its own docstring.** A
generated file that does not admit to being one is a file somebody edits, and
R19's promise is that a hand-edit is a *finding* rather than a fix — which is
only fair if the file said so.
"""

from __future__ import annotations

from collections.abc import Sequence

#: The sentence every generated module carries. ⭐ One copy, so two generated
#: modules cannot come to describe the same rule differently.
GENERATED = (
    "⛔ Generated by studyforge onboarding. A hand-edit here is a finding",
    "against that skill rather than a fix (R19); change corpus.json and",
    "regenerate.",
)


class ComposeError(ValueError):
    """A module that will not be composed, and which piece is missing."""


def module(*, summary: str, imports: Sequence[str], body: Sequence[str]) -> str:
    """Return one generated module's text.

    ⛔ Refuses an empty summary or an empty body rather than emitting a module
    that looks finished and asserts nothing.
    """
    if not summary.strip():
        raise ComposeError("a generated module states what it is; the summary is empty")
    if not [line for line in body if line.strip()]:
        raise ComposeError("a generated module with an empty body asserts nothing")
    head = [
        f'"""{summary}',
        "",
        *GENERATED,
        '"""',
        "",
        "from __future__ import annotations",
        "",
        *imports,
        "",
        "",
    ]
    return "\n".join([*head, *body]) + "\n"
