r"""Assemble one generated Python module: its contract, its imports, its checks.

**What it does.** `module(...)` returns the text of a module that states what
it is, says it is generated, and carries the body it was given.

**How you use it.** Called by the renderers in this package; never directly by
a skill's reader.

**Depends on.** The standard library. ⛔ No I/O, and nothing source-specific
(R1).

## ⭐ Composed, never pasted

⚠️ **A contract inside one long string literal is a contract no rule reaches**,
and nothing lints a module that does not exist yet. The adapter skill's
`parts.compose` made the same argument for a generated adapter and **raises** when a piece is
missing; this is its twin for the two modules an onboarding generates.

⛔ **Every module it composes says it is generated, in its own docstring.** A
generated file that does not admit to being one is a file somebody edits, and
R19's promise is that a hand-edit is a *finding* rather than a fix — which is
only fair if the file said so.

## ⭐ Every module it composes runs without a test runner (`W467`, `ISO-32/4`)

⚠️ **Measured at a corpus:** the generated checks needed pytest, and a Python
holding only the installed wheel has none, so a stranger could not run the one
check that says whether their library is the pinned one. ⭐ **So each module ends
in `RUNNER`**: `python3 tests/<the module>.py` runs every `test_*` it defines,
prints one line each and exits non-zero on a failure. ⭐ **A check that cannot
be read here calls `skip(why)`**, which is pytest's skip under pytest and the
runner's own otherwise, so the one module is the same check under both.
⛔ The framework's own source stays standard library only: the runner is
generated text, and pytest is imported only where it is already running.
"""

from __future__ import annotations

from collections.abc import Sequence

#: The sentence every generated module carries. ⭐ One copy, so two generated
#: modules cannot come to describe the same rule differently.
GENERATED = (
    "⛔ Generated by studyforge onboarding. A hand-edit here is a finding",
    "against that skill rather than a fix (R19); change corpus.json and",
    "regenerate.",
)


#: What every composed module ends with: `skip`, and the runner a Python with no
#: pytest runs it by. ⭐ Functions resolve their globals when called, so a check
#: above may call `skip` though it is defined below.
RUNNER = (
    "",
    "",
    "class Skipped(Exception):",
    '    """A check that cannot be read here, and why."""',
    "",
    "",
    "def skip(why):",
    '    """Skip this check: the runner\'s skip when run as a script, else pytest\'s."""',
    "    if __name__ == '__main__':",
    "        raise Skipped(why)",
    "    try:",
    "        import pytest",
    "    except ImportError:",
    "        raise Skipped(why) from None",
    "    pytest.skip(why)",
    "",
    "",
    "def run(checks):",
    '    """Run every test_ function in `checks`, one line each; return the exit code."""',
    "    failed = 0",
    "    for name, check in sorted(checks.items()):",
    "        if not name.startswith('test_') or not callable(check):",
    "            continue",
    "        try:",
    "            check()",
    "        except Skipped as why:",
    "            print('skip', name, '-', why)",
    "        except Exception as error:",
    "            failed += 1",
    "            print('FAIL', name, '-', type(error).__name__, error)",
    "        else:",
    "            print('ok', name)",
    "    return 1 if failed else 0",
    "",
    "",
    "if __name__ == '__main__':",
    "    raise SystemExit(run(dict(globals())))",
)


class ComposeError(ValueError):
    """A module that will not be composed, and which piece is missing."""


def module(*, summary: str, imports: Sequence[str], body: Sequence[str]) -> str:
    """Return one generated module's text.

    ⛔ Refuses an empty summary or an empty body rather than emitting a module
    that looks finished and asserts nothing.
    """
    if not summary.strip():
        raise ComposeError("a generated module states what it is; the summary is empty")
    if not [line for line in body if line.strip()]:
        raise ComposeError("a generated module with an empty body asserts nothing")
    head = [
        f'"""{summary}',
        "",
        *GENERATED,
        '"""',
        "",
        "from __future__ import annotations",
        "",
        *imports,
        "",
        "",
    ]
    return "\n".join([*head, *body, *RUNNER]) + "\n"
