"""The generated document: one row per ruling, every one a quote and an address.

**What it does.** Turns the derivation in `derive` into the Markdown of
`docs/tasks/rulings-index.md` — a header whose every number is generated, and
one table row per ruling in the derived series.

**How you use it.** `text(root)` returns the document; `__main__` writes it and
this package's check compares it with what is on disk.

**Depends on.** `derive` for the rows, `quote` for the cell width it reports,
and `pathlib.PurePosixPath` for the link. ⛔ Nothing reads the document in
order to produce it, so a hand-edit cannot survive: the next run reverts it,
and the floor reports it in between (R19).

## ⛔ Why the address is a link and not a line number

`W78` and Ruling 163 both hold that a line-number citation into a file the
document does not own has no instrument behind it. ⭐ **An anchor has one**:
`check_pointers` resolves every `#anchor` in this repository against the
headings of the document it names, so each of these rows is re-verified on every
floor run — ⚠️ **which is why the rows carry one link each and never a `:line`.**
"""

from __future__ import annotations

from pathlib import Path, PurePosixPath

from tools.quality.rulings.derive import (
    INDEX_PATH,
    Entry,
    entries,
    records,
    series,
    sites,
)
from tools.quality.rulings.quote import QUOTE_LIMIT

__all__ = ["link", "text"]

_HEADER = """# The rulings index

**GENERATED by `python3 -m tools.quality.rulings`. Do not edit — regenerate.**

⛔ **Every cell below is the record's OWN WORDING, quoted.** ⭐ **Not one row
paraphrases a ruling** (Ruling 195): a paraphrase can be kept freshly wrong,
a quote cannot diverge, and a pointer resolves at read time. ⚠️ **A cell's `\\|`
is the record's `|`, escaped so a quoted table row survives being quoted; a
trailing `…` marks a quote cut at {limit} characters and nothing else.**

⛔ **What this index does NOT carry, deliberately: a `where it landed` column.**
⚠️ **The round-17 index had one, and six of its own 42 rows were already wrong
about it on the day it shipped.** ⭐ **A claim about whether a ruling reached an
artifact is re-measured by nobody** — it is the column that cannot be kept true,
and Rulings 161, 150 and 136 all say the remedy is to remove the subject rather
than to maintain the copy.

## What a reader does with this

⭐ **Resolve a bare `(Ruling N)` to a statement, in one hop, without reading the
handoff chain every brief forbids reading.** The `form` column says what the
quote is: `heading` means the row quotes the section's own heading and the
address IS that heading; `section` means the ruling is stated inside the
section's prose or in one of its tables, and the quoted line is where its number
is written.

## ⛔ The two series, and they are never merged

⭐ **`R1`–`R21` are the SPEC's rulings and are a different series**
(`docs/specs/2026-09-08-studyforge-v1-design.md`). ⛔ **Nothing here indexes
them:** the population comes from the literal spelling `Ruling <digits>`, which
no `R7`-style citation can match. ⚠️ **A brief that cites `R11` is citing the
spec; a brief that cites `Ruling 11` is citing this table.**

## The derivation, and what the next office does when 198 is minted

⭐ **{count} rulings, `1`–`{tail}`, derived from {files} ruling records** —
every row re-derived on each run, and ⛔ **no count in this document is typed.**
{outside}

⛔ **Nothing here is hand-maintained, so a ruling minted after this run makes
the document STALE, never incomplete:** `tools.quality`'s floor fails
until `python3 -m tools.quality.rulings` is re-run, and that is the whole maintenance
procedure.

| # | the record's own words | form | read it in |
|---|---|---|---|
"""


def link(record: str) -> str:
    """Return the record's path as the index document has to write it.

    Relative to the index's own directory, because that is what a Markdown link
    resolves against — and what `check_pointers` resolves it against too.
    """
    return str(PurePosixPath(record).relative_to(PurePosixPath(INDEX_PATH).parent))


def _row(entry: Entry) -> str:
    """Return one table row: number, quote, form, anchored address."""
    site = entry.site
    form = "heading" if site.on_heading else "section"
    target = f"{link(site.record)}#{site.anchor}"
    return f"| {entry.number} | {site.quote} | {form} | [round {site.round}]({target}) |"


def _outside(numbers: tuple[int, ...]) -> str:
    """Return the sentence naming numbers written as rulings but outside the series."""
    if not numbers:
        return (
            "⭐ **The series is contiguous and nothing was written outside it**, so every "
            "`Ruling <n>` spelled in a record has a row here."
        )
    spelled = ", ".join(f"`{number}`" for number in numbers)
    return (
        f"⚠️ **Written as a ruling but OUTSIDE the contiguous series, and therefore not "
        f"indexed: {spelled}.** ⛔ **Printed rather than dropped** — at least one of these "
        f"is an *impossible* control in a probe table, and a population that discards a "
        f"member in silence is the defect this index exists to close."
    )


def text(root: Path) -> str:
    """Return the whole generated document for the tree at `root`."""
    found = records(root)
    rows = entries(root)
    written = {site.number for record in found for site in sites(record)}
    header = _HEADER.format(
        limit=QUOTE_LIMIT,
        count=len(rows),
        tail=rows[-1].number if rows else 0,
        files=len(found),
        outside=_outside(series(written).outside),
    )
    return header + "\n".join(_row(entry) for entry in rows) + "\n"
